services:
  payment_gateway_api:
    container_name: payment_gateway_api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mock_payment_gateways:
        condition: service_healthy
    ports:
      - '8080:80'
    env_file:
      - ./.env.docker
    healthcheck:
      test: curl http://localhost:80/health
