// Code generated by MockGen. DO NOT EDIT.
// Source: PaymentGateway/internal/payment-gateway-api/integrations (interfaces: Gateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	domains "PaymentGateway/internal/payment-gateway-api/domains"
	models "PaymentGateway/internal/payment-gateway-api/integrations/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// Deposit mocks base method.
func (m *MockGateway) Deposit(arg0 *domains.Deposit) (models.DepositResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", arg0)
	ret0, _ := ret[0].(models.DepositResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deposit indicates an expected call of Deposit.
func (mr *MockGatewayMockRecorder) Deposit(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockGateway)(nil).Deposit), arg0)
}

// GetGatewayIdentifier mocks base method.
func (m *MockGateway) GetGatewayIdentifier() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayIdentifier")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGatewayIdentifier indicates an expected call of GetGatewayIdentifier.
func (mr *MockGatewayMockRecorder) GetGatewayIdentifier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayIdentifier", reflect.TypeOf((*MockGateway)(nil).GetGatewayIdentifier))
}

// Withdraw mocks base method.
func (m *MockGateway) Withdraw(arg0 *domains.Withdraw) (models.WithdrawResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", arg0)
	ret0, _ := ret[0].(models.WithdrawResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockGatewayMockRecorder) Withdraw(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockGateway)(nil).Withdraw), arg0)
}
