// Code generated by MockGen. DO NOT EDIT.
// Source: PaymentGateway/internal/payment-gateway-api/repositories (interfaces: DepositRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domains "PaymentGateway/internal/payment-gateway-api/domains"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockDepositRepository is a mock of DepositRepository interface.
type MockDepositRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDepositRepositoryMockRecorder
}

// MockDepositRepositoryMockRecorder is the mock recorder for MockDepositRepository.
type MockDepositRepositoryMockRecorder struct {
	mock *MockDepositRepository
}

// NewMockDepositRepository creates a new mock instance.
func NewMockDepositRepository(ctrl *gomock.Controller) *MockDepositRepository {
	mock := &MockDepositRepository{ctrl: ctrl}
	mock.recorder = &MockDepositRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositRepository) EXPECT() *MockDepositRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepositRepository) Create(arg0 context.Context, arg1 *domains.Deposit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDepositRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepositRepository)(nil).Create), arg0, arg1)
}

// GetById mocks base method.
func (m *MockDepositRepository) GetById(arg0 context.Context, arg1 uuid.UUID) (*domains.Deposit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1)
	ret0, _ := ret[0].(*domains.Deposit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockDepositRepositoryMockRecorder) GetById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockDepositRepository)(nil).GetById), arg0, arg1)
}

// Update mocks base method.
func (m *MockDepositRepository) Update(arg0 context.Context, arg1 *domains.Deposit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDepositRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepositRepository)(nil).Update), arg0, arg1)
}
